<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>Surveil</RootNamespace>
		<ApplicationIcon>Assets\tray-icon.ico</ApplicationIcon>
		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<PublishProfile>win-$(Platform).pubxml</PublishProfile>
		<UseWinUI>true</UseWinUI>
		<EnableMsixTooling>true</EnableMsixTooling>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<HasPackageAndPublishMenuSuites>true</HasPackageAndPublishMenuSuites>
		<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
		<PackageCertificateThumbprint Condition="'$(PackageCertificateKeyFile)' == ''">14388DA69AEF54A81F72B91ACEB9AB18DE735978</PackageCertificateThumbprint>
		<AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
	</PropertyGroup>
	
	<ItemGroup>
		<Content Include="Assets\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<ProjectCapability Include="Msix" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" />
		<PackageReference Include="LibVLCSharp" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="VideoLAN.LibVLC.Windows" />
		<PackageReference Include="H.NotifyIcon.WinUI" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" />
		<PackageReference Include="Microsoft.WindowsAppSDK" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Views\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Surveil.Core\Surveil.Core.csproj" />
	  <ProjectReference Include="..\Surveil.Unifi\Surveil.Unifi.csproj" />
	</ItemGroup>

	<PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
	</PropertyGroup>
</Project>